import { routeConstants } from './routeConstants';
import {
  HomeCategoryImages,
  HomeDealBanner,
  HomeImages,
  HomeNewArrivalsImages,
  HomeOfferImages,
  InstaBanner,
} from '../assets/images/images';
/* MAIN MENU SIDEBAR */
const currencyList = [
  {
    type: 'USD',
    symbol: '&dollar;',
  },
  {
    type: 'EUR',
    symbol: '&euro;',
  },
  {
    type: 'EGP',
    symbol: '&pound;',
  },
];
const LanguageList = [
  {
    type: 'English',
  },
  {
    type: 'Arabic',
  },
  {
    type: 'French',
  },
  {
    type: 'Espaniol',
  },
];
const footerSocialList = [
  {
    icon: 'jam:pinterest-square',
  },
  {
    icon: 'hugeicons:facebook-01',
  },
  {
    icon: 'hugeicons:new-twitter-rectangle',
  },
  {
    icon: 'hugeicons:youtube',
  },
];
/* SIDEBAR DATA */
const menuItems = [
  {
    title: 'Home',
    link: routeConstants.HOME,
  },
  {
    title: 'Shop',
    link: routeConstants.PRODUCTS,
  },
  {
    title: 'About',
    link: routeConstants.ABOUT,
  },
  {
    title: 'Contact',
    link: routeConstants.CONTACT,
  },
  {
    title: 'FAQ',
    link: routeConstants.FAQ,
  },
  {
    title: 'Blog',
    link: routeConstants.BLOG,
  },
];

const categoriesItems = [
  {
    title: 'WATCHES',
    link: routeConstants.PRODUCTS,
    expanded: true,
    submenu: [
      {
        title: 'Watches Brand',
        link: routeConstants.PRODUCTS,
        expanded: true,
        secondSubmenu: [
          {
            title: 'Watch one',
            link: '#',
            expanded: true,
          },
          {
            title: 'Watch one',
            link: '#',
          },
          {
            title: 'Watch one',
            link: '#',
          },
        ],
      },
      {
        title: 'Watches Display',
        link: routeConstants.PRODUCTS,
        expanded: true,
        secondSubmenu: [
          {
            title: 'Watch one',
            link: '#',
            expanded: true,
          },
          {
            title: 'Watch one',
            link: '#',
          },
          {
            title: 'Watch one',
            link: '#',
          },
        ],
      },
      {
        title: 'Watches Style',
        link: routeConstants.PRODUCTS,
        expanded: true,
        secondSubmenu: [
          {
            title: 'Watch one',
            link: '#',
            expanded: true,
          },
          {
            title: 'Watch one',
            link: '#',
          },
          {
            title: 'Watch one',
            link: '#',
          },
        ],
      },
    ],
  },
  {
    title: 'FOOTWEAR',
    link: routeConstants.PRODUCTS,
    expanded: true,
    submenu: [
      {
        title: 'Brand One',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Two',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Three',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Four',
        link: routeConstants.PRODUCTS,
      },
    ],
  },
  {
    title: 'CLOTHING',
    link: routeConstants.PRODUCTS,
    expanded: true,
    submenu: [
      {
        title: 'Brand One',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Two',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Three',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Four',
        link: routeConstants.PRODUCTS,
      },
    ],
  },
  {
    title: 'ACCESSORIES',
    link: routeConstants.PRODUCTS,
    expanded: true,
    submenu: [
      {
        title: 'Brand One',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Two',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Three',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Four',
        link: routeConstants.PRODUCTS,
      },
    ],
  },
  {
    title: 'HOME & DECOR',
    link: routeConstants.PRODUCTS,
    expanded: true,
    submenu: [
      {
        title: 'Brand One',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Two',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Three',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Four',
        link: routeConstants.PRODUCTS,
      },
    ],
  },
  {
    title: 'BAGS',
    link: routeConstants.PRODUCTS,
    expanded: true,
    submenu: [
      {
        title: 'Brand One',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Two',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Three',
        link: routeConstants.PRODUCTS,
      },
      {
        title: 'Brand Four',
        link: routeConstants.PRODUCTS,
      },
    ],
  },
  {
    title: 'KITCHAN',
    link: routeConstants.PRODUCTS,
    expanded: false,
    submen: [],
  },
];
/* HOME PAGE */
const bannerSectionData = [
  {
    bannerImage: HomeImages.banner1,
    sale: '15%',
    type: 'shirt',
    offer: 'by one get one',
    free: true,
  },
  {
    bannerImage: HomeImages.banner2,
    sale: '10%',
    type: 'jeans',
    offer: 'sale on brand',
    free: true,
  },
];
const newArrivalsData = [
  {
    id: 0,
    frontImg: HomeNewArrivalsImages.Product1_front,
    backImg: HomeNewArrivalsImages.Product1_back,
    category: 'shirt',
    rate: 4.5,
    label: 'v-neck',
    price: 180,
    quantity: 1,
    badge: false,
    sale: '30',
  },
  {
    id: 1,
    frontImg: HomeNewArrivalsImages.Product2_front,
    backImg: HomeNewArrivalsImages.Product2_back,
    category: 'jeans',
    rate: 3.5,
    label: 'allen solly',
    price: 51,
    quantity: 1,
    badge: false,
    sale: '10 - 15',
  },
  {
    id: 2,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 3,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 4,
    frontImg: HomeNewArrivalsImages.Product5_front,
    backImg: HomeNewArrivalsImages.Product5_back,
    category: 'shirt',
    rate: 2.5,
    label: 'hot sleeve black shirt',
    price: 26,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 5,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 6,
    frontImg: HomeNewArrivalsImages.Product7_front,
    backImg: HomeNewArrivalsImages.Product7_back,
    category: 't-shirt',
    rate: 3.1,
    label: 'black t-shirt',
    price: 25,
    quantity: 1,
    badge: false,
    sale: 15,
  },
  {
    id: 7,
    frontImg: HomeNewArrivalsImages.Product8_front,
    backImg: HomeNewArrivalsImages.Product8_back,
    category: 'jacket',
    rate: 2.2,
    label: 'light camofluge jacket',
    price: 55,
    quantity: 1,
    badge: false,
    sale: 10,
  },
];

const homeCategoryData = [
  {
    banner: HomeCategoryImages.categoryBanner1,
    title: 'jacket',
    category: 'fashion',
  },
  {
    banner: HomeCategoryImages.categoryBanner2,
    title: 'shirt',
    category: 'shirts',
  },
  {
    banner: HomeCategoryImages.categoryBanner3,
    title: 'jeans',
    category: 'jacket',
  },
  {
    banner: HomeCategoryImages.categoryBanner4,
    title: 'walltet',
    category: 'fashion',
  },
  {
    banner: HomeCategoryImages.categoryBanner5,
    title: 'crop-shirt',
    category: 'shirts',
  },
];

const homeOfferData = [
  {
    banner: HomeOfferImages.offerBanner1,
    title: 'v-neck from',
    price: '180',
  },
  {
    banner: HomeOfferImages.offerBanner2,
    title: 'Allen Solly from',
    price: '51',
  },

  {
    banner: HomeOfferImages.offerBanner3,
    title: 'T-shirt',
    discount: '15',
  },
  {
    banner: HomeOfferImages.offerBanner4,
    title: 'hoodie',
    discount: '10',
  },
];
const homeDealData = [
  {
    banner: HomeDealBanner.homeDealBanner,
    discount: 10,
    title: 'deal of the day',
    price: 180,
    type: 'shirt',
  },
];
const instaShopData = [
  {
    banner: InstaBanner.instaBanner1,
    title: 'V-neck',
    price: '180',
    discount: '15',
  },
  {
    banner: InstaBanner.instaBanner2,
    title: 'Allen Solly',
    price: '180',
    discount: '10',
  },
  {
    banner: InstaBanner.instaBanner3,
    title: 'T-shirt',
    price: '51',
    discount: '10',
  },
  {
    banner: InstaBanner.instaBanner4,
    title: 'Hoodie',
    price: '65',
    discount: '20',
  },
  {
    banner: InstaBanner.instaBanner5,
    title: 'Graphic Shirt',
    price: '35',
    discount: '10',
  },
];

const servicesData = [
  {
    icon: 'hugeicons:customer-service',
    title: 'Customer Servcies',
    desc: 'Top notch customer service.',
  },
  {
    icon: 'hugeicons:store-location-02',
    title: 'Pickup At Any Store',
    desc: 'Free shipping on orders over $65',
  },
  {
    icon: 'ri:secure-payment-line',
    title: 'Secured Payment',
    desc: 'We accept all major credit cards',
  },
  {
    icon: 'hugeicons:truck-return',
    title: 'Free Returns',
    desc: '30-days free return policy.',
  },
];

/* PRODUCTS PAGE */
const productOptionsView = [
  {
    type: 'Alphabetically A-Z',
  },
  {
    type: 'Alphabetically Z-A',
  },
  {
    type: 'Price, High To Low',
  },
  {
    type: 'Price, Low To High',
  },
  {
    type: 'Date, Old To New',
  },
  {
    type: 'Date, New To Old',
  },
];
const productTypeView = [
  {
    type: 'Jeans',
  },
  {
    type: 'T-Shirt',
  },
  {
    type: 'Shirt',
  },
  {
    type: 'Jackets',
  },
  {
    type: 'Hoodie',
  },
];

const productsShop = [
  {
    id: 0,
    frontImg: HomeNewArrivalsImages.Product1_front,
    backImg: HomeNewArrivalsImages.Product1_back,
    category: 'shirt',
    rate: 4.5,
    label: 'v-neck',
    price: 180,
    quantity: 1,
    badge: false,
    sale: '30',
  },
  {
    id: 1,
    frontImg: HomeNewArrivalsImages.Product2_front,
    backImg: HomeNewArrivalsImages.Product2_back,
    category: 'jeans',
    rate: 3.5,
    label: 'allen solly',
    price: 51,
    quantity: 1,
    badge: false,
    sale: '10 - 15',
  },
  {
    id: 2,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 3,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 4,
    frontImg: HomeNewArrivalsImages.Product5_front,
    backImg: HomeNewArrivalsImages.Product5_back,
    category: 'shirt',
    rate: 2.5,
    label: 'hot sleeve black shirt',
    price: 26,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 5,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 6,
    frontImg: HomeNewArrivalsImages.Product7_front,
    backImg: HomeNewArrivalsImages.Product7_back,
    category: 't-shirt',
    rate: 3.1,
    label: 'black t-shirt',
    price: 25,
    quantity: 1,
    badge: false,
    sale: 15,
  },
  {
    id: 7,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 8,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 9,
    frontImg: HomeNewArrivalsImages.Product5_front,
    backImg: HomeNewArrivalsImages.Product5_back,
    category: 'shirt',
    rate: 2.5,
    label: 'hot sleeve black shirt',
    price: 26,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 10,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 11,
    frontImg: HomeNewArrivalsImages.Product8_front,
    backImg: HomeNewArrivalsImages.Product8_back,
    category: 'jacket',
    rate: 2.2,
    label: 'light camofluge jacket',
    price: 55,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 12,
    frontImg: HomeNewArrivalsImages.Product1_front,
    backImg: HomeNewArrivalsImages.Product1_back,
    category: 'shirt',
    rate: 4.5,
    label: 'v-neck',
    price: 180,
    quantity: 1,
    badge: false,
    sale: '30',
  },
  {
    id: 13,
    frontImg: HomeNewArrivalsImages.Product2_front,
    backImg: HomeNewArrivalsImages.Product2_back,
    category: 'jeans',
    rate: 3.5,
    label: 'allen solly',
    price: 51,
    quantity: 1,
    badge: false,
    sale: '10 - 15',
  },
  {
    id: 141,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 15,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 16,
    frontImg: HomeNewArrivalsImages.Product5_front,
    backImg: HomeNewArrivalsImages.Product5_back,
    category: 'shirt',
    rate: 2.5,
    label: 'hot sleeve black shirt',
    price: 26,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 17,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 18,
    frontImg: HomeNewArrivalsImages.Product7_front,
    backImg: HomeNewArrivalsImages.Product7_back,
    category: 't-shirt',
    rate: 3.1,
    label: 'black t-shirt',
    price: 25,
    quantity: 1,
    badge: false,
    sale: 15,
  },
  {
    id: 19,
    frontImg: HomeNewArrivalsImages.Product8_front,
    backImg: HomeNewArrivalsImages.Product8_back,
    category: 'jacket',
    rate: 2.2,
    label: 'light camofluge jacket',
    price: 55,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 20,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 21,
    frontImg: HomeNewArrivalsImages.Product7_front,
    backImg: HomeNewArrivalsImages.Product7_back,
    category: 't-shirt',
    rate: 3.1,
    label: 'black t-shirt',
    price: 25,
    quantity: 1,
    badge: false,
    sale: 15,
  },

  {
    id: 22,
    frontImg: HomeNewArrivalsImages.Product8_front,
    backImg: HomeNewArrivalsImages.Product8_back,
    category: 'jacket',
    rate: 2.2,
    label: 'light camofluge jacket',
    price: 55,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 23,
    frontImg: HomeNewArrivalsImages.Product1_front,
    backImg: HomeNewArrivalsImages.Product1_back,
    category: 'shirt',
    rate: 4.5,
    label: 'v-neck',
    price: 180,
    quantity: 1,
    badge: false,
    sale: '30',
  },
  {
    id: 24,
    frontImg: HomeNewArrivalsImages.Product2_front,
    backImg: HomeNewArrivalsImages.Product2_back,
    category: 'jeans',
    rate: 3.5,
    label: 'allen solly',
    price: 51,
    quantity: 1,
    badge: false,
    sale: '10 - 15',
  },
  {
    id: 25,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 26,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 27,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 28,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 29,
    frontImg: HomeNewArrivalsImages.Product5_front,
    backImg: HomeNewArrivalsImages.Product5_back,
    category: 'shirt',
    rate: 2.5,
    label: 'hot sleeve black shirt',
    price: 26,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 30,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 31,
    frontImg: HomeNewArrivalsImages.Product7_front,
    backImg: HomeNewArrivalsImages.Product7_back,
    category: 't-shirt',
    rate: 3.1,
    label: 'black t-shirt',
    price: 25,
    quantity: 1,
    badge: false,
    sale: 15,
  },
  {
    id: 32,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 33,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 34,
    frontImg: HomeNewArrivalsImages.Product5_front,
    backImg: HomeNewArrivalsImages.Product5_back,
    category: 'shirt',
    rate: 2.5,
    label: 'hot sleeve black shirt',
    price: 26,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 35,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 36,
    frontImg: HomeNewArrivalsImages.Product8_front,
    backImg: HomeNewArrivalsImages.Product8_back,
    category: 'jacket',
    rate: 2.2,
    label: 'light camofluge jacket',
    price: 55,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 37,
    frontImg: HomeNewArrivalsImages.Product1_front,
    backImg: HomeNewArrivalsImages.Product1_back,
    category: 'shirt',
    rate: 4.5,
    label: 'v-neck',
    price: 180,
    quantity: 1,
    badge: false,
    sale: '30',
  },
  {
    id: 38,
    frontImg: HomeNewArrivalsImages.Product2_front,
    backImg: HomeNewArrivalsImages.Product2_back,
    category: 'jeans',
    rate: 3.5,
    label: 'allen solly',
    price: 51,
    quantity: 1,
    badge: false,
    sale: '10 - 15',
  },
  {
    id: 39,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 40,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
  {
    id: 41,
    frontImg: HomeNewArrivalsImages.Product5_front,
    backImg: HomeNewArrivalsImages.Product5_back,
    category: 'shirt',
    rate: 2.5,
    label: 'hot sleeve black shirt',
    price: 26,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 42,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 43,
    frontImg: HomeNewArrivalsImages.Product7_front,
    backImg: HomeNewArrivalsImages.Product7_back,
    category: 't-shirt',
    rate: 3.1,
    label: 'black t-shirt',
    price: 25,
    quantity: 1,
    badge: false,
    sale: 15,
  },
  {
    id: 44,
    frontImg: HomeNewArrivalsImages.Product8_front,
    backImg: HomeNewArrivalsImages.Product8_back,
    category: 'jacket',
    rate: 2.2,
    label: 'light camofluge jacket',
    price: 55,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 45,
    frontImg: HomeNewArrivalsImages.Product6_front,
    backImg: HomeNewArrivalsImages.Product6_back,
    category: 'hoodie',
    rate: 4.2,
    label: 'full sleeve yellow',
    price: 30,
    quantity: 1,
    badge: false,
    sale: 20,
  },
  {
    id: 46,
    frontImg: HomeNewArrivalsImages.Product7_front,
    backImg: HomeNewArrivalsImages.Product7_back,
    category: 't-shirt',
    rate: 3.1,
    label: 'black t-shirt',
    price: 25,
    quantity: 1,
    badge: false,
    sale: 15,
  },

  {
    id: 47,
    frontImg: HomeNewArrivalsImages.Product8_front,
    backImg: HomeNewArrivalsImages.Product8_back,
    category: 'jacket',
    rate: 2.2,
    label: 'light camofluge jacket',
    price: 55,
    quantity: 1,
    badge: false,
    sale: 10,
  },
  {
    id: 48,
    frontImg: HomeNewArrivalsImages.Product1_front,
    backImg: HomeNewArrivalsImages.Product1_back,
    category: 'shirt',
    rate: 4.5,
    label: 'v-neck',
    price: 180,
    quantity: 1,
    badge: false,
    sale: '30',
  },
  {
    id: 49,
    frontImg: HomeNewArrivalsImages.Product2_front,
    backImg: HomeNewArrivalsImages.Product2_back,
    category: 'jeans',
    rate: 3.5,
    label: 'allen solly',
    price: 51,
    quantity: 1,
    badge: false,
    sale: '10 - 15',
  },
  {
    id: 50,
    frontImg: HomeNewArrivalsImages.Product3_front,
    backImg: HomeNewArrivalsImages.Product3_back,
    category: 'jackets',
    rate: 3,
    label: 'pubm yellow jacket',
    price: 45,
    quantity: 1,
    badge: false,
    sale: 25,
  },
  {
    id: 51,
    frontImg: HomeNewArrivalsImages.Product4_front,
    backImg: HomeNewArrivalsImages.Product4_back,
    category: 'shirt',
    rate: 0,
    label: 'full sleeve black shirt',
    price: 18,
    quantity: 1,
    badge: false,
    sale: 5,
  },
];

/* FAQ PAGE */
const faqData = [
  {
    title: 'Mauris vestibulum ex ut metus aliquam eleifend?',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, orci ac elementum convallis, dolor enim volutpat sapien, id porttitor eros risus convallis nibh. Nullam dui diam, semper sed neque ut, fringilla rutrum velit.',
  },
  {
    title: 'Aliquam tincidunt tellus in augue interdum vestibulum ut vel?',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, orci ac elementum convallis, dolor enim volutpat sapien, id porttitor eros risus convallis nibh. Nullam dui diam, semper sed neque ut, fringilla rutrum velit.',
  },
  {
    title: 'Website response taking time, how to improve?',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, orci ac elementum convallis, dolor enim volutpat sapien, id porttitor eros risus convallis nibh. Nullam dui diam, semper sed neque ut, fringilla rutrum velit.',
  },
  {
    title: 'Maecenas egestas malesuada hendrerit ?',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mattis, orci ac elementum convallis, dolor enim volutpat sapien, id porttitor eros risus convallis nibh. Nullam dui diam, semper sed neque ut, fringilla rutrum velit.',
  },
];
export const Data = {
  menuItems,
  categoriesItems,
  currencyList,
  footerSocialList,
  LanguageList,
  bannerSectionData,
  newArrivalsData,
  homeCategoryData,
  homeOfferData,
  homeDealData,
  instaShopData,
  servicesData,
  productOptionsView,
  productTypeView,
  productsShop,
  faqData,
};
